apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  minReadySeconds: 3
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          # pointer to the config of HOW we want the mount to be implemeneted
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb #this MUST line up with the path specified in the spring boot production.properties file which points to mongodb.default, etc.. path
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP
