apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  minReadySeconds: 3
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-queue:release1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  minReadySeconds: 3
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template: #template for pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
